http.port=8081

db.host=localhost
db.port=3306
db.database=solicitudes_db
db.user=root
db.password=root123

evidence.path=C:/proyectos/evidence

sftp.host=localhost
sftp.port=2222
sftp.user=mule
sftp.password=mule123
sftp.path=/upload