spring.application.name=solicitudes-api

# ========================================
# Base de datos MySQL
# ========================================
spring.datasource.url=jdbc:mysql://localhost:3306/solicitudes_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================================
# JPA / Hibernate
# ========================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================================
# Ruta para archivos de evidencia de solicitudes registradas
# ========================================
evidence.path=C:/proyectos/evidence

# ========================================
# SFTP
# ========================================
sftp.host=localhost
sftp.port=2222
sftp.username=mule
sftp.password=mule123
sftp.remote-path=/upload
